---
title: "Reproducible Research Project-1"
author: "Sefat-E-Barket"
output: 
  html_document:
    keep_md: true
---




```{r}
library(ggplot2)
activityData <- read.csv("C:\Users\PC\Downloads\activity.csv")
activityData
```


```{r}
stepsTotal <- activityData[, c(lapply(.SD, sum, na.rm = FALSE)), .SDcols = c("steps"), by = .(date)]
head(stepsTotal, 10)
```

```{r}
ggplot(stepsTotal, aes(x = steps)) +
    geom_histogram(fill = "springgreen3", binwidth = 1250) +
    labs(x = "Number of Steps", y = "Frequency") +
    ggtitle("Histogram of Total Daily Steps") +
    theme(plot.title = element_text(hjust = 0.5))
```


```{r}
stepsTotal[, .(MeanSteps = mean(steps, na.rm = TRUE), 
               MedianSteps = median(steps, na.rm = TRUE))]
```


```{r}
fiveminIntdata <- activityData[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval)] 
ggplot(fiveminIntdata, aes(x = interval , y = steps)) + 
  geom_line(color="springgreen3", size=1) + 
  labs(x = "Time Interval", y = "Number of Steps") +
  ggtitle("Average Daily Steps Pattern") +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
fiveminIntdata[steps == max(steps), .(maxInterval = interval)]
```
í¹°s)

```{r}
activityData[is.na(steps), .N ]    
```


```{r}
activityData[is.na(steps), "steps"] <- activityData[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
```


```{r}
data.table::fwrite(x = activityData, file = "fitness-data/modifiedData.csv", quote = FALSE)
```



```{r}
stepsTotalmodified <- activityData[, c(lapply(.SD, sum, na.rm = FALSE)), .SDcols = c("steps"), by = .(date)] 
```



```{r}
ggplot(stepsTotalmodified, aes(x = steps)) +
    geom_histogram(fill = "steelblue3", binwidth = 1250) +
    labs(x = "Number of Steps", y = "Frequency") +
    ggtitle("Modified Histogram of Total Daily Steps") +
    theme(plot.title = element_text(hjust = 0.5))
```


```{r}
stepsTotalmodified[, .(MeanStepsModified = mean(steps, na.rm = TRUE), 
               MedianStepsModified = median(steps, na.rm = TRUE))]
```

```{r}
stepsTotal[, .(MeanSteps = mean(steps, na.rm = TRUE), 
               MedianSteps = median(steps, na.rm = TRUE))]
```



```{r}
weekDayEnd <- data.table::fread(input = "fitness-data/activity.csv")
weekDayEnd[, date := as.POSIXct(date, format = "%Y-%m-%d")]
weekDayEnd[, `Day of Week`:= weekdays(x = date)]
weekDayEnd[grepl(pattern = "Monday|Tuesday|Wednesday|Thursday|Friday", x = `Day of Week`), "Weekday or Weekend"] <- "Week Day"
weekDayEnd[grepl(pattern = "Saturday|Sunday", x = `Day of Week`), "Weekday or Weekend"] <- "Week End"
weekDayEnd[, `weekday or weekend` := as.factor(`Weekday or Weekend`)]
```


```{r}
weekDayEnd[is.na(steps), "steps"] <- weekDayEnd[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
fiveminInt <- weekDayEnd[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval, `Weekday or Weekend`)] 
ggplot(fiveminInt , aes(x = interval , y = steps, color=`Weekday or Weekend`)) + 
  geom_line() + labs(x = "Time Interval", y = "Number of Steps") + 
  facet_wrap(~`Weekday or Weekend` , ncol = 1, nrow=2) +
  ggtitle("Comparison of Average Daily Steps") +
  theme(plot.title = element_text(hjust = 0.5))
```